export enum Category {
    ANY = "Any Category",
    GENERAL_KNOWLEDGE = "General Knowledge",
    ENTERTAINMENT_BOOKS = "Entertainment Books",
    ENTERTAINMENT_FILM = "Entertainment Film",
    ENTERTAINMENT_MUSIC = "Entertainment Music",
    ENTERTAINMENT_MUSICALS_THEATRES = "Entertainment Musicals Theatres",
    ENTERTAINMENT_TELEVISION = "Entertainment Television",
    ENTERTAINMENT_VIDEO_GAMES = "Entertainment Video Games",
    ENTERTAINMENT_BOARD_GAMES = "Entertainment Board Games",
    SCIENCE_NATURE = "Science Nature",
    SCIENCE_COMPUTERS = "Science Computers",
    SCIENCE_MATHEMATICS = "Science Mathematics",
    MYTHOLOGY = "Mythology",
    SPORTS = "Sports",
    GEOGRAPHY = "Geography",
    HISTORY = "History",
    POLITICS = "Politics",
    ART = "Art",
    CELEBRITIES = "Celebrities",
    ANIMALS = "Animals",
    VEHICLES = "Vehicles",
    ENTERTAINMENT_COMICS = "Entertainment Comics",
    SCIENCE_GADGETS = "Science Gadgets",
    ENTERTAINMENT_JAPANESE_ANIME_MANGA = "Entertainment Japanese Anime Manga",
    ENTERTAINMENT_CARTOON_ANIMATIONS = "Entertainment Cartoon Animations"
}